spring.application.name=javasocketchat

spring.datasource.url = jdbc:mysql://localhost:3306/javachat ? useSSL=false & serverTimezone=UTC & allowPublicKeyRetrieval=true
spring.datasource.username = root
spring.datasource.password = MySQL
spring.datasource.driver = com.mysql.cj.jdbc.Driver