spring.application.name=javasocketchat

# HikariDataSource连接池配置
# 数据库连接配置
datasource.url=jdbc:mysql://localhost:3306/javachat?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
datasource.username=root
datasource.password=MySQL
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 连接池配置
datasource.maximum-pool-size=20
datasource.minimum-idle=5
datasource.connection-timeout=30000
datasource.idle-timeout=600000
datasource.max-lifetime=1800000